In [ ]:
pip install requests beautifulsoup4 lxml langdetect python-dateutil openpyxl

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (6.0.2)
Requirement already satisfied: langdetect in /usr/local/lib/python3.12/dist-packages (1.0.9)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (2.9.0.post0)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2025.11.12)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from langdetect) (1.17.0)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

**Step 1: Load the Excel file**

In [ ]:
import pandas as pd

# Change path if needed
INPUT_PATH = "/content/REST_Media_Backlinks (1).xlsx"

df = pd.read_excel(INPUT_PATH)
print("Loaded rows:", len(df))
display(df.head())

Loaded rows: 28

,Page ascore,Source title,Source url,Target url,Anchor,External links,Internal links,Nofollow,Sponsored,Ugc,Text,Frame,Form,Image,Sitewide,First seen,Last seen,New link,Lost link
0,0,5000 domain name ideas for word - rest | DomenSky,https://domains.bugcrew.net/domains/rest,https://restmedia.st/,.io,24995,17,False,False,False,True,False,False,False,False,2025-08-22,2025-09-26,False,False
1,0,9 letter domain name ideas for word - rest | D...,https://domains.bugcrew.net/domains/rest/9,https://restmedia.st/,.io,4570,4,False,False,False,True,False,False,False,False,2025-08-26,2025-09-26,False,False
2,0,SYNLOGOS,https://dstormer6em3i4km.onion.pw/sources,https://restmedia.st/feed/,âŒ”,717,12,False,False,False,False,False,False,True,False,2025-06-30,2025-09-27,False,False
3,0,SYNLOGOS,https://dstormer6em3i4km.onion.pw/sources,https://restmedia.st/,https://restmedia.io,717,12,False,False,False,True,False,False,False,False,2025-06-30,2025-09-27,False,False
4,0,SYNLOGOS,https://elstormer6vrre53.onion.pw/sources,https://restmedia.st/feed/,âŒ”,717,12,False,False,False,False,False,False,True,False,2025-06-30,2025-09-21,False,False

In [ ]:
columns_to_drop = [
    'Anchor',
    'External links',
    'Internal links',
    'Nofollow',
    'Sponsored',
    'Ugc',
    'Text',
    'Frame',
    'Form',
    'Image',
    'Sitewide',
    'First seen',
    'Last seen',
    'New link',
    'Lost link'
]

df = df.drop(columns=columns_to_drop, errors='ignore')

print("Columns after dropping:", df.columns.tolist())
display(df.head())

Columns after dropping: ['Page ascore', 'Source title', 'Source url', 'Target url']

,Page ascore,Source title,Source url,Target url
0,0,5000 domain name ideas for word - rest | DomenSky,https://domains.bugcrew.net/domains/rest,https://restmedia.st/
1,0,9 letter domain name ideas for word - rest | D...,https://domains.bugcrew.net/domains/rest/9,https://restmedia.st/
2,0,SYNLOGOS,https://dstormer6em3i4km.onion.pw/sources,https://restmedia.st/feed/
3,0,SYNLOGOS,https://dstormer6em3i4km.onion.pw/sources,https://restmedia.st/
4,0,SYNLOGOS,https://elstormer6vrre53.onion.pw/sources,https://restmedia.st/feed/

**Step 2: Import libraries and silence XML-as-HTML warning**

In [ ]:
from bs4 import BeautifulSoup, XMLParsedAsHTMLWarning
import warnings
import requests
from dateutil import parser
from langdetect import detect

# Silence BeautifulSoup's XMLParsedAsHTMLWarning (optional, but tidy)
warnings.filterwarnings("ignore", category=XMLParsedAsHTMLWarning)

**Step 3: Fetch URL content (with basic error handling)**

In [ ]:
def fetch_url(url, timeout=12):
    try:
        headers = {"User-Agent": "Mozilla/5.0 (compatible; ExtractionBot/1.0)"}
        r = requests.get(url, timeout=timeout, headers=headers)
        r.raise_for_status()
        return r.text
    except Exception as e:
        print(f"[FETCH ERROR] {url} -> {e}")
        return None

# quick test (uncomment one URL to test)
# print(fetch_url("https://restmedia.st/")[:500])

In [ ]:
def is_xml_content(text):
    if not text:
        return False
    s = text.lstrip()[:100].lower()
    return s.startswith("<?xml") or s.startswith("<rss") or s.startswith("<feed") or "<rss" in s[:200] or "<feed" in s[:200]

In [ ]:
def parse_title(soup):
    # HTML <title> or XML <title> inside items/entry
    title_tag = soup.find("title")
    if title_tag and title_tag.get_text(strip=True):
        return title_tag.get_text(strip=True)
    # fallback: meta og:title
    meta = soup.find("meta", property="og:title") or soup.find("meta", attrs={"name":"twitter:title"})
    if meta and meta.get("content"):
        return meta["content"].strip()
    return None

In [ ]:
def parse_text(soup, xml_mode=False, max_chars=20000):
    text_pieces = []
    if not xml_mode:
        # HTML: get paragraphs and article tags
        for p in soup.find_all("p"):
            t = p.get_text(" ", strip=True)
            if t:
                text_pieces.append(t)
        # also try article tag if paragraphs empty
        if not text_pieces:
            article = soup.find("article")
            if article:
                text_pieces.append(article.get_text(" ", strip=True))
    else:
        # XML: look for item/entry descriptions or content:encoded
        for tagname in ("content:encoded", "encoded", "description", "summary", "content"):
            for tag in soup.find_all(tagname):
                t = tag.get_text(" ", strip=True)
                if t:
                    text_pieces.append(t)
        # sometimes title+link per item is the only content; include item titles
        if not text_pieces:
            for item in soup.find_all(["item","entry"]):
                t = ""
                t += (item.find("title").get_text(" ", strip=True) if item.find("title") else "")
                desc = item.find("description") or item.find("summary")
                if desc:
                    t += " " + desc.get_text(" ", strip=True)
                if t.strip():
                    text_pieces.append(t.strip())

    text = " ".join(text_pieces).strip()
    if not text:
        return None
    return text[:max_chars]

In [ ]:
def parse_date(soup):
    # Common date tags
    candidates = []
    # HTML5 time tag
    for t in soup.find_all("time"):
        if t.has_attr("datetime"):
            candidates.append(t["datetime"])
        else:
            candidates.append(t.get_text(" ", strip=True))
    # RSS/Atom
    for name in ("pubDate","published","updated","dc:date","date"):
        for tag in soup.find_all(name):
            candidates.append(tag.get_text(" ", strip=True))
    # Meta tags
    meta_names = [
        ("meta", {"property":"article:published_time"}),
        ("meta", {"name":"pubdate"}),
        ("meta", {"name":"publishdate"}),
        ("meta", {"name":"publication_date"})
    ]
    for tagname, attrs in meta_names:
        tag = soup.find(tagname, attrs=attrs)
        if tag and tag.get("content"):
            candidates.append(tag["content"])

    # Try to parse candidates with dateutil.parser
    for c in candidates:
        if not c or len(c.strip())<4:
            continue
        try:
            dt = parser.parse(c, fuzzy=True)
            return dt.isoformat()
        except Exception:
            continue
    return None

In [ ]:
def detect_language(text):
    try:
        if not text or len(text.strip()) < 30:
            return None
        return detect(text)
    except Exception:
        return None

In [ ]:
def extract_from_url(url):
    raw = fetch_url(url)
    if raw is None:
        return {"title": None, "text": None, "date": None, "language": None}

    xml_mode = is_xml_content(raw)
    parser_type = "xml" if xml_mode else "html.parser"
    soup = BeautifulSoup(raw, parser_type)

    title = parse_title(soup)
    text = parse_text(soup, xml_mode=xml_mode)
    date = parse_date(soup)
    language = detect_language(text)

    return {"title": title, "text": text, "date": date, "language": language}

In [ ]:
from tqdm import tqdm

results = []
for idx, row in tqdm(df.iterrows(), total=len(df)):
    source = row.get("Source url") or row.get("Source_url") or row.get("SourceUrl")
    target = row.get("Target url") or row.get("Target_url") or row.get("TargetUrl")

    res = {"row_index": idx, "source_url": source, "target_url": target}

    if source and isinstance(source, str) and source.strip():
        out = extract_from_url(source.strip())
        res.update({
            "source_title": out["title"],
            "source_text": out["text"],
            "source_date": out["date"],
            "source_language": out["language"]
        })
    else:
        res.update({"source_title":None,"source_text":None,"source_date":None,"source_language":None})

    if target and isinstance(target, str) and target.strip():
        out = extract_from_url(target.strip())
        res.update({
            "target_title": out["title"],
            "target_text": out["text"],
            "target_date": out["date"],
            "target_language": out["language"]
        })
    else:
        res.update({"target_title":None,"target_text":None,"target_date":None,"target_language":None})

    results.append(res)

final_df = pd.DataFrame(results)

# Arrange columns in a proper order
cols = [
    "row_index",
    "source_url", "source_title", "source_text", "source_date", "source_language",
    "target_url", "target_title", "target_text", "target_date", "target_language"
]
final_df = final_df[cols]

# Save
OUT_PATH = "extracted_results_separate_steps.xlsx"
final_df.to_excel(OUT_PATH, index=False)
print("Saved extraction to:", OUT_PATH)

  0%|          | 0/28 [00:00<?, ?it/s]

[FETCH ERROR] https://domains.bugcrew.net/domains/rest -> HTTPSConnectionPool(host='domains.bugcrew.net', port=443): Max retries exceeded with url: /domains/rest (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7a80a3482270>: Failed to resolve 'domains.bugcrew.net' ([Errno -2] Name or service not known)"))

  4%|▎         | 1/28 [00:03<01:22,  3.05s/it]

[FETCH ERROR] https://domains.bugcrew.net/domains/rest/9 -> HTTPSConnectionPool(host='domains.bugcrew.net', port=443): Max retries exceeded with url: /domains/rest/9 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7a80a1e84980>: Failed to resolve 'domains.bugcrew.net' ([Errno -2] Name or service not known)"))

  7%|▋         | 2/28 [00:04<01:00,  2.34s/it]

[FETCH ERROR] https://dstormer6em3i4km.onion.pw/sources -> HTTPSConnectionPool(host='dstormer6em3i4km.onion.pw', port=443): Max retries exceeded with url: /sources (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)')))

 11%|█         | 3/28 [00:06<00:50,  2.01s/it]

[FETCH ERROR] https://dstormer6em3i4km.onion.pw/sources -> HTTPSConnectionPool(host='dstormer6em3i4km.onion.pw', port=443): Max retries exceeded with url: /sources (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)')))

 14%|█▍        | 4/28 [00:07<00:42,  1.76s/it]

[FETCH ERROR] https://elstormer6vrre53.onion.pw/sources -> HTTPSConnectionPool(host='elstormer6vrre53.onion.pw', port=443): Max retries exceeded with url: /sources (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)')))

 39%|███▉      | 11/28 [00:20<00:27,  1.61s/it]

[FETCH ERROR] https://restmedia.st/wp-content/uploads/2025/07/04_07_3_Foreign-Support-Influence.jpg -> 404 Client Error: Not Found for url: https://restmedia.st/wp-content/uploads/2025/07/04_07_3_Foreign-Support-Influence.jpg

 54%|█████▎    | 15/28 [00:26<00:18,  1.43s/it]

[FETCH ERROR] https://restmedia.st/wp-content/uploads/2025/06/REST_4_1.jpg -> 404 Client Error: Not Found for url: https://restmedia.st/wp-content/uploads/2025/06/REST_4_1.jpg

 61%|██████    | 17/28 [00:32<00:24,  2.20s/it]

[FETCH ERROR] https://e-play.io/british-gambling-money-and-armenias-political-financing-system/ -> HTTPSConnectionPool(host='e-play.io', port=443): Max retries exceeded with url: /british-gambling-money-and-armenias-political-financing-system/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)')))

 64%|██████▍   | 18/28 [00:33<00:19,  1.92s/it]

[FETCH ERROR] https://e-play.pl/brytyjskie-pieniadze-hazardowe-i-system-finansowania-polityki-w-armenii/ -> 403 Client Error: Forbidden for url: https://e-play.pl/brytyjskie-pieniadze-hazardowe-i-system-finansowania-polityki-w-armenii/

 68%|██████▊   | 19/28 [00:35<00:15,  1.72s/it]

[FETCH ERROR] https://e-play.pl/brytyjskie-pieniadze-hazardowe-i-system-finansowania-polityki-w-armenii/ -> 403 Client Error: Forbidden for url: https://e-play.pl/brytyjskie-pieniadze-hazardowe-i-system-finansowania-polityki-w-armenii/

 71%|███████▏  | 20/28 [00:36<00:13,  1.71s/it]

[FETCH ERROR] https://e-play.pl/brytyjskie-pieniadze-hazardowe-i-system-finansowania-polityki-w-armenii/ -> 403 Client Error: Forbidden for url: https://e-play.pl/brytyjskie-pieniadze-hazardowe-i-system-finansowania-polityki-w-armenii/

 75%|███████▌  | 21/28 [00:37<00:10,  1.53s/it]

[FETCH ERROR] https://vaseljenska.net/2025/07/26/dosije-srpskog-pravosudja-zapadna-istraga-medija-rest-o-dubokoj-transformaciji-srpskog-tuzilastva/ -> 403 Client Error: Forbidden for url: https://vaseljenska.net/2025/07/26/dosije-srpskog-pravosudja-zapadna-istraga-medija-rest-o-dubokoj-transformaciji-srpskog-tuzilastva/

 79%|███████▊  | 22/28 [00:39<00:08,  1.43s/it]

[FETCH ERROR] https://vaseljenska.net/2025/06/27/evropa-na-ivici-promena-kako-vlade-suzbijaju-konzervativnu-opoziciju/ -> 403 Client Error: Forbidden for url: https://vaseljenska.net/2025/06/27/evropa-na-ivici-promena-kako-vlade-suzbijaju-konzervativnu-opoziciju/

 82%|████████▏ | 23/28 [00:40<00:06,  1.34s/it]

[FETCH ERROR] https://vaseljenska.net/2025/06/28/oberer-angriff-2-0-ultimatumi-srbiji-na-vidovdan-i-dalje-stizu/ -> 403 Client Error: Forbidden for url: https://vaseljenska.net/2025/06/28/oberer-angriff-2-0-ultimatumi-srbiji-na-vidovdan-i-dalje-stizu/

 93%|█████████▎| 26/28 [00:45<00:03,  1.57s/it]

[FETCH ERROR] https://www.marx21.it/internazionale/e-trasparenza-o-censura-la-battaglia-della-moldavia-contro-la-disinformazione/ -> 403 Client Error: Forbidden for url: https://www.marx21.it/internazionale/e-trasparenza-o-censura-la-battaglia-della-moldavia-contro-la-disinformazione/

100%|██████████| 28/28 [00:51<00:00,  1.84s/it]

Saved extraction to: extracted_results_separate_steps.xlsx